name: Setup dependencies
description: Setup dependencies required for many jobs
inputs:
  restore-cache:
    description: Whether to try to restore the cache
    default: "true"
  save-cache:
    description: Whether to save the cache at the end
    default: "false"

runs:
  using: composite
  steps:
    - name: Set up Rust
      run: rustup update stable
      shell: bash
    - uses: Swatinem/rust-cache@v2
      if: inputs.restore-cache == 'true'
      with:
        save-if: "${{ inputs.save-cache }}"

    # mandb sometimes causes delays when installing via apt
    - name: Disable mandb
      run: sudo apt-get remove --purge man-db
      shell: bash
    - name: Install APT dependencies
      run: sudo apt-get install protobuf-compiler libcurl4-openssl-dev
      shell: bash
