[package]
edition = { workspace = true }
license = { workspace = true }
name = "scion-proto"
publish = false
version = { workspace = true }

[dependencies]
bytes = { workspace = true }
chrono = { workspace = true }
scion-grpc = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true }
rand_xorshift = { workspace = true }
test-utils = { workspace = true }

[[bench]]
name = "checksum"
harness = false

[lints]
workspace = true
