[package]
name = "scion-proto"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytes = "1.5.0"
chrono = { version = "0.4.31", default-features = false }
scion-grpc = { version = "0.1.0", path = "../scion-grpc" }
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.48"
tonic = "0.10.2"
tracing = "0.1.40"

[dev-dependencies]
prost-types = "0.12.2"
