[workspace]
resolver = "3"
members = [
    "crates/scion",
    "crates/scion-grpc",
    "crates/scion-proto",
    "crates/test-utils"
]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
async-trait = "0.1.89"
bytes = "1.10.1"
chrono = { version = "0.4.41", default-features = false }
criterion = "0.7.0"
futures = "0.3.31"
mockall = "0.13.1"
prost = "0.14"
prost-types = "0.14"
rand = "0.9.2"
rand_xorshift = "0.4.0"
serde = { version = "1.0.219", features = ["derive"] }
scion-grpc = { version = "0.1.0", path = "crates/scion-grpc" }
scion-proto = { version = "0.1.0", path = "crates/scion-proto" }
sha2 = "0.10.9"
test-utils = { version = "0.1.0", path = "crates/test-utils" }
thiserror = "2.0.15"
tokio = "1.47.1"
tonic = "0.14"
tonic-prost = "0.14"
tonic-prost-build = "0.14"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[workspace.lints.rust]
missing_docs = "warn"
