[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]

[lints]
workspace = true

[dev-dependencies]
tokio = { version = "1.35.1", features = ["test-util", "tokio-macros", "macros"] }
