[package]
name = "scion"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
scion-grpc = { version = "0.1.0", path = "../scion-grpc" }
scion-proto = { version = "0.1.0", path = "../scion-proto" }
thiserror = "1.0.48"
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros"] }
tonic = "0.10.2"
tracing = "0.1.40"
