[package]
edition = { workspace = true }
license = { workspace = true }
name = "scion-grpc"
publish = false
version = { workspace = true }

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }

[lib]
bench = false

[lints.rust]
missing_docs = "allow"
