name: Lint

on: [pull_request]

permissions:
  contents: read

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    name: Check conventional commit messages
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5
        with:
          fetch-depth: 0
      - name: Check commit messages
        uses: aevea/commitsar@916c7b483225a30d3a17f407fa25f5b25888ea69 # pin@v0.20
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@fdd4d3ddf614fbcd8c29e4b106d3bbe0cb2c605d6 # pin@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  editorconfig:
    runs-on: ubuntu-latest
    name: Check editorconfig
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5
      - uses: editorconfig-checker/action-editorconfig-checker@d2ed4fd072ae6f887e9407c909af0f585d2ad9f4 # pin@v2
      - run: editorconfig-checker

  typos:
    runs-on: ubuntu-latest
    name: Check spelling
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5
      - uses: crate-ci/typos@65f69f021b736bdbe548ce72200500752d42b40e # pin@v1.35.7

  check-all:
    name: Check if all lint jobs succeeded
    if: always()
    needs:
      - conventional-commits
      - editorconfig
      - typos
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether all needed jobs succeeded
      uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # pin@v1
      with:
        jobs: ${{ toJSON(needs) }}
